name: NQC CI

on:
  workflow_dispatch:
  push:
    # branches: [ master ]
  pull_request:
    # branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
    - name: Get the latest from version control
      uses: actions/checkout@v4
    - name: Update build environment
      run:  sudo apt-get --assume-yes update
    - name: Install build dependencies
      run:  sudo apt-get --assume-yes install flex bison binutils-h8300-hms emscripten
    - name: Execute the build
      run:  make DEFAULT_SERIAL_NAME='"/dev/ttyS0"' DEFAULT_USB_NAME='"/dev/usb/legousbtower0"' DEFAULT_PORT_NAME='"usb"'
    - name: Archive native build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nqc-native-${{ matrix.os }}
        path: build/bin/
    - name: Archive JavaScript-WebAssembly build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nqc-JS-WebAssembly-${{ matrix.os }}
        path: build/js-wasm/
